# Generated by Django 3.2.19 on 2023-06-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('IQ_result', models.SmallIntegerField(blank=True, null=True)),
                ('IQ_test_pass_time', models.TimeField(blank=True, null=True)),
                ('EQ_result', models.CharField(blank=True, max_length=40, null=True)),
                ('EQ_test_pass_time', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
